version: '{build}-{branch}'
os: Windows Server 2012 R2
platform: x64
init:
install:
  - set PATH=C:\Ruby22-x64\bin;%PATH%
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install
build_script:
  - rake build
